### ISSUE TITLE
Tenor gives me no gifs. Just a poop image instead

### ISSUE THREAD

**Issue by Lynx530** [Jinzulen/TenorJS#7]
![errortenor](https://user-images.githubusercontent.com/67557159/85955631-90e2ad00-b99d-11ea-89ac-ed89757d4c45.PNG)
everything's alright. No error no nothing at all. but when I embed this tenor API gifs. It shows me this instead of choosing a random gif and giving it to me. Someone solve it
am getting this type of error when i used the tenor api. Is there any fix? please tell me. I am in need of this..please

**Comment by Jinzulen** [comment]
This isn't a Tenor or a TenorJS problem.

Discord uses the poop image when it can't load an image. You must not be passing the rich embed the direct image link. The link the embed loads should look like this `https://media.tenor.com/images/f0fc8c17ddf47b6229e5cf46d74698dc/tenor.gif` not like this `https://tenor.com/LliJ.gif` because otherwise you'd be attempting to load a webpage as an image.

![image](https://user-images.githubusercontent.com/32587697/85958167-4eb07000-b98b-11ea-9c1a-b4a1aa70504e.png)

**Comment by Lynx530** [comment]
Can you give me the code? am just a rookie..i would be grateful if you gave the code

**Comment by Jinzulen** [comment]
I already gave usage examples [here](https://github.com/Jinzulen/TenorJS#23-random-gif). Grab the GIF url from the Post object (`Post.media[0].gif.url`) and push it into the embed image.
